In [7]:
import pandas as pd

In [43]:
df = pd.read_csv('TMDB_movie_dataset_2000_2025.csv')

In [44]:
df.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'budget', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'primary_country', 'primary_company'],
      dtype='object')

## Loại bỏ cột `overview` và cột `poster_path`
Cột `overview` là mô tả ngắn gọn về phim, có ý nghĩa về mặt ngôn ngữ tự nhiên, nhưng không thể trực quan hóa nếu không có độ đo cụ thể. Do đó, cột này sẽ được loại bỏ.  
Cột `poster_path` là đường dẫn đến ảnh bìa giới thiệu phim, không có ý nghĩa về mặt thống kê, do đó cũng được loại bỏ.

In [45]:
df = df[['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date', 'revenue', 'runtime', 'adult', 'budget', 'original_language',
       'original_title', 'popularity', 'genres', 'production_companies', 'production_countries', 'spoken_languages']]
df

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,budget,original_language,original_title,popularity,genres,production_companies,production_countries,spoken_languages
0,27205,Inception,"8,364",34495,Released,2010-07-15,825532764,148,False,160000000,en,Inception,"83,952","Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili"
1,157336,Interstellar,"8,417",32571,Released,2014-11-05,701729206,169,False,165000000,en,Interstellar,"140,241","Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English
2,155,The Dark Knight,"8,512",30619,Released,2008-07-16,1004558444,152,False,185000000,en,The Dark Knight,"130,643","Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin"
3,19995,Avatar,"7,573",29815,Released,2009-12-15,2923706026,162,False,237000000,en,Avatar,"79,932","Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish"
4,24428,The Avengers,"7,71",29166,Released,2012-04-25,1518815515,143,False,220000000,en,The Avengers,"98,082","Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422426,764246,La Muerte Está en Los Catres,"0,0",0,Released,2020-11-26,0,63,False,0,es,La Muerte Está en Los Catres,"0,6",Documentary,Cusicanqui Films,Chile,Spanish
422427,764265,The Blue Butterflies Path,"0,0",0,Released,2020-11-09,0,11,False,0,pt,Na Trilha das Borboletas Azuis,"0,6",Animation,NaN,Brazil,Portuguese
422428,764250,Scorpio,"0,0",0,Released,2010-07-06,0,42,False,0,fa,اسکورپیو,"0,6",Documentary,NaN,Iran,Persian
422429,764255,In the Eve For Love,"0,0",0,Released,2020-05-20,0,18,False,0,zh,除夕夜狂奔,"0,662",Romance,NaN,NaN,NaN
422430,764256,The Chosen,"0,0",0,Released,2020-11-09,0,13,False,0,fr,Les Choisis,"0,6","Animation, Science Fiction",NaN,France,French

## Tách các thể loại phim trong cột `genres`
Thuộc `genres` chứa nhiều giá trị, do đó chúng ta sẽ tách các giá trị của thuộc tính này ra.

In [48]:
genre_df = df[['id']]

for id in genre_df['id']:
    genres = df.loc[df['id'] == id, 'genres'].to_list()[0]
    if type(genres) != str:
        continue

    for genre in genres.split(', '):
        genre = genre.strip()
        if genre not in genre_df.keys():
            genre_df[genre] = False
        genre_df.loc[genre_df['id'] == id, genre] = True

C:\Users\PC\AppData\Local\Temp\ipykernel_24824\3910261002.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genre_df[genre] = False
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\3910261002.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genre_df[genre] = False
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\3910261002.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genre_df[genre] = False
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\3910261002.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genre_df[genre] = False
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\3910261002.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genre_df[genre] = False
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\3910261002.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genre_df[genre] = False
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\3910261002.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genre_df[genre] = False
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\3910261002.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genre_df[genre] = False
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\3910261002.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genre_df[genre] = False
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\3910261002.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genre_df[genre] = False
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\3910261002.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genre_df[genre] = False
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\3910261002.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genre_df[genre] = False
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\3910261002.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genre_df[genre] = False
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\3910261002.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genre_df[genre] = False
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\3910261002.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genre_df[genre] = False

In [50]:
genre_df

,id,Action,Science Fiction,Adventure,Drama,Crime,Thriller,Fantasy,Comedy,Western,Mystery,War,Animation,Family,Horror,Music,History,Romance,TV Movie,Documentary
0,27205,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,157336,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,155,True,False,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False
3,19995,True,True,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
4,24428,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422426,764246,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
422427,764265,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
422428,764250,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
422429,764255,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
422430,764256,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False

In [51]:
genre_df.to_csv('movie_genre_table.csv')

## Tách các nhà sản xuất phim trong cột `production_companies`
Thuộc `production_companies` cũng chứa nhiều giá trị, do đó chúng ta sẽ tách các giá trị của thuộc tính này ra.

In [66]:
product_companies_df = df[['id']]
for i in range(1, 16):
    product_companies_df[f'product_company_n{i}'] = pd.NA

for id in product_companies_df['id']:
    companies = df.loc[df['id'] == id, 'production_companies'].to_list()[0]
    if type(companies) != str:
        continue

    companies = companies.split(', ')
    for i in range(len(companies)):
        product_companies_df.loc[product_companies_df['id'] == id, f'product_company_n{i + 1}'] = companies[i].strip()

C:\Users\PC\AppData\Local\Temp\ipykernel_24824\1234989612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_companies_df[f'product_company_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\1234989612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_companies_df[f'product_company_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\1234989612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_companies_df[f'product_company_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\1234989612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_companies_df[f'product_company_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\1234989612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_companies_df[f'product_company_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\1234989612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_companies_df[f'product_company_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\1234989612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_companies_df[f'product_company_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\1234989612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_companies_df[f'product_company_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\1234989612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_companies_df[f'product_company_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\1234989612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_companies_df[f'product_company_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\1234989612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_companies_df[f'product_company_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\1234989612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_companies_df[f'product_company_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\1234989612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_companies_df[f'product_company_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\1234989612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_companies_df[f'product_company_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\1234989612.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_companies_df[f'product_company_n{i}'] = pd.NA

In [67]:
product_companies_df

,id,product_company_n1,product_company_n2,product_company_n3,product_company_n4,product_company_n5,product_company_n6,product_company_n7,product_company_n8,product_company_n9,...,product_company_n21,product_company_n22,product_company_n23,product_company_n24,product_company_n25,product_company_n26,product_company_n27,product_company_n28,product_company_n29,product_company_n30
0,27205,Legendary Pictures,Syncopy,Warner Bros. Pictures,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,157336,Legendary Pictures,Syncopy,Lynda Obst Productions,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,155,DC Comics,Legendary Pictures,Syncopy,Isobel Griffiths,Warner Bros. Pictures,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,19995,Dune Entertainment,Lightstorm Entertainment,20th Century Fox,Ingenious Media,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,24428,Marvel Studios,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422426,764246,Cusicanqui Films,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
422427,764265,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
422428,764250,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
422429,764255,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
422430,764256,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
product_companies_df.to_csv('production_companies.csv')

## Tách các nước sản xuất phim trong cột `production_countries`
Thuộc `production_countries` cũng chứa nhiều giá trị, do đó chúng ta sẽ tách các giá trị của thuộc tính này ra.

In [72]:
product_countries_df = df[['id']]
for i in range(1, 9):
    product_countries_df[f'product_country_n{i}'] = pd.NA

for id in product_companies_df['id']:
    countries = df.loc[df['id'] == id, 'production_countries'].to_list()[0]
    if type(countries) != str:
        continue

    countries = countries.split(', ')
    for i in range(len(countries)):
        product_countries_df.loc[product_countries_df['id'] == id, f'product_country_n{i + 1}'] = countries[i].strip()

C:\Users\PC\AppData\Local\Temp\ipykernel_24824\2630874902.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_countries_df[f'product_country_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\2630874902.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_countries_df[f'product_country_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\2630874902.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_countries_df[f'product_country_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\2630874902.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_countries_df[f'product_country_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\2630874902.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_countries_df[f'product_country_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\2630874902.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_countries_df[f'product_country_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\2630874902.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_countries_df[f'product_country_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\2630874902.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_countries_df[f'product_country_n{i}'] = pd.NA
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\2630874902.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_countries_df.loc[product_countries_df['id'] == id, f'product_country_n{i + 1}'] = countries[i].strip()
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\2630874902.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_countries_df.loc[product_countries_df['id'] == id, f'product_country_n{i + 1}'] = countries[i].strip()
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\2630874902.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_countries_df.loc[product_countries_df['id'] == id, f'product_country_n{i + 1}'] = countries[i].strip()
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\2630874902.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_countries_df.loc[product_countries_df['id'] == id, f'product_country_n{i + 1}'] = countries[i].strip()
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\2630874902.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_countries_df.loc[product_countries_df['id'] == id, f'product_country_n{i + 1}'] = countries[i].strip()
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\2630874902.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_countries_df.loc[product_countries_df['id'] == id, f'product_country_n{i + 1}'] = countries[i].strip()
C:\Users\PC\AppData\Local\Temp\ipykernel_24824\2630874902.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_countries_df.loc[product_countries_df['id'] == id, f'product_country_n{i + 1}'] = countries[i].strip()

In [74]:
product_countries_df

,id,product_country_n1,product_country_n2,product_country_n3,product_country_n4,product_country_n5,product_country_n6,product_country_n7,product_country_n8,product_country_n9,...,product_country_n50,product_country_n51,product_country_n52,product_country_n53,product_country_n54,product_country_n55,product_country_n56,product_country_n57,product_country_n58,product_country_n59
0,27205,United Kingdom,United States of America,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,157336,United Kingdom,United States of America,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,155,United Kingdom,United States of America,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,19995,United States of America,United Kingdom,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,24428,United States of America,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422426,764246,Chile,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
422427,764265,Brazil,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
422428,764250,Iran,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
422429,764255,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
422430,764256,France,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
product_countries_df.to_csv('production_countries.csv')